# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mplwidget import MplWidget
from mplwidget2 import MplWidget2

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(638, 454)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 611, 381))
        self.tabWidget.setObjectName("tabWidget")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.progressBar_2 = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar_2.setGeometry(QtCore.QRect(10, 320, 471, 21))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.mplwidget2 = MplWidget2(self.tab_2)
        self.mplwidget2.setGeometry(QtCore.QRect(10, 10, 581, 301))
        self.mplwidget2.setObjectName("mplwidget2")
        self.mplwidget2.toolbar.hide()
        self.Dataset_Start = QtWidgets.QPushButton(self.tab_2)
        self.Dataset_Start.setGeometry(QtCore.QRect(500, 320, 91, 21))
        self.Dataset_Start.setObjectName("Dataset_Start")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.progressBar_Epoch = QtWidgets.QProgressBar(self.tab)
        self.progressBar_Epoch.setGeometry(QtCore.QRect(10, 320, 471, 20))
        self.progressBar_Epoch.setProperty("value", 24)
        self.progressBar_Epoch.setObjectName("progressBar_Epoch")
        self.Train_Start = QtWidgets.QPushButton(self.tab)
        self.Train_Start.setGeometry(QtCore.QRect(500, 320, 91, 21))
        self.Train_Start.setObjectName("Train_Start")
        self.process = QtWidgets.QTextEdit(self.tab)
        self.process.setGeometry(QtCore.QRect(10, 10, 581, 301))
        self.process.setLineWrapMode(QtWidgets.QTextEdit.FixedPixelWidth)
        self.process.setLineWrapColumnOrWidth(500)
        self.process.setReadOnly(True)
        self.process.setObjectName("process")
        self.Train_Stop = QtWidgets.QPushButton(self.tab)
        self.Train_Stop.setGeometry(QtCore.QRect(500, 320, 91, 21))
        self.Train_Stop.setObjectName("Train_Stop")
        self.tabWidget.addTab(self.tab, "")
        self.TEST = QtWidgets.QWidget()
        self.TEST.setObjectName("TEST")
        self.mplwidget = MplWidget(self.TEST)
        self.mplwidget.setGeometry(QtCore.QRect(10, 10, 581, 261))
        self.mplwidget.setObjectName("mplwidget")
        self.mplwidget.toolbar.hide()
        self.label_3 = QtWidgets.QLabel(self.TEST)
        self.label_3.setGeometry(QtCore.QRect(310, 310, 41, 21))
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.TEST)
        self.textEdit.setGeometry(QtCore.QRect(10, 290, 281, 41))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.TEST)
        self.label_2.setGeometry(QtCore.QRect(300, 280, 51, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.TEST)
        self.lineEdit.setGeometry(QtCore.QRect(370, 280, 101, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.TEST)
        self.lineEdit_2.setGeometry(QtCore.QRect(370, 310, 101, 26))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.TEST)
        self.label.setGeometry(QtCore.QRect(10, 270, 71, 18))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.TEST)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 290, 91, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.TEST, "")
        self.TRAIN = QtWidgets.QWidget()
        self.TRAIN.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));")
        self.TRAIN.setObjectName("TRAIN")
        self.tabWidget.addTab(self.TRAIN, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 638, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Dataset_Start.setText(_translate("MainWindow", "START"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "PREPROCESSOR"))
        self.Train_Start.setText(_translate("MainWindow", "START"))
        self.Train_Stop.setText(_translate("MainWindow", "STOP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "TRAIN"))
        self.label_3.setText(_translate("MainWindow", "Label"))
        self.label_2.setText(_translate("MainWindow", "Predict"))
        self.label.setText(_translate("MainWindow", "Data Path"))
        self.pushButton_2.setText(_translate("MainWindow", "START"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TEST), _translate("MainWindow", "TEST"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TRAIN), _translate("MainWindow", "Other"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
